language: python

# for container-y googdness:
sudo: false

addons:
  postgresql: "9.2"

python:
  - "3.4"
  - "2.7"

# command to install dependencies
install: "pip install -Ue .[test,build]"

before_script:
- sh -c "psql -c 'create database testdb' -U postgres"
- sh -c 'psql -d testdb -c "CREATE EXTENSION btree_gist;" -U postgres'
- psql --version

# command to run tests, e.g. python setup.py test
script: DB_URL=postgres://postgres@localhost/testdb nosetests --with-cov --cov=mortar_import

after_success:
  - coveralls

deploy:
  provider: pypi
  user: chrisw
  password:
    secure:
  on:
    tags: true
    repo: Mortar/mortar_import
    python: "3.4"
  skip_cleanup: true
  distributions: "sdist bdist_wheel"
