version: 2.1

orbs:
  python: cjw296/python-ci@3

jobs:
  run-tests:
    parameters:
      python:
        type: string
      postgres:
        type: string
    docker:
      - image: cimg/python:<< parameters.python >>
        environment:
          DB_URL: postgresql://postgres@localhost/circle_test
      - image: cimg/postgres:<< parameters.postgres >>
    steps:
      - run: "sudo apt install postgresql-client"
      - run: "pip install sockpuppet && sockpuppet wait -p 5432 --timeout 300"
      - run: "psql -d circle_test -c \"CREATE EXTENSION btree_gist;\" -h localhost -U postgres"
      - python/pip-run-tests

common: &common
  jobs:
    - run-tests:
        matrix:
          parameters:
            python: ['3.7', '3.10']
            postgres: ["11.15"]

    - python/coverage:
        name: coverage
        requires:
          - run-tests

    - python/pip-docs:
        name: docs
        requires:
          - coverage

    - python/release:
        name: release
        config: .carthorse.yml
        requires:
          - docs
        filters:
          branches:
            only: master

workflows:
  push:
    <<: *common
  periodic:
    <<: *common
    triggers:
      - schedule:
          cron: "0 0 3 * *"
          filters:
            branches:
              only: master
